#!/usr/bin/env python3
import argparse
import json
from datetime import datetime
from pathlib import Path


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def status_icon(status: str) -> str:
    value = str(status or "unknown")
    return {
        "passed": "PASS",
        "failed": "FAIL",
        "attention": "CHECK",
        "Passed": "PASS",
        "Failed": "FAIL",
        "Blocked": "BLOCKED",
        "Untested": "UNTESTED",
        "Inconclusive": "INCONCLUSIVE",
    }.get(value, value.upper())


def requirement_result(ledger: dict | None, audit_summary: dict | None) -> str:
    if not ledger:
        return "UNAUDITED"
    if audit_summary and not audit_summary.get("passed"):
        return "AUDIT_FAIL"
    statuses = [item.get("status") for item in ledger.get("requirements", [])]
    if not statuses:
        return "NO_REQUIREMENTS"
    if any(status == "Failed" for status in statuses):
        return "FAIL"
    if all(status == "Passed" for status in statuses):
        return "PASS"
    return "CHECK"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a Markdown QA report from a plan and Playwright probe results.")
    parser.add_argument("--plan", required=True)
    parser.add_argument("--results", required=True)
    parser.add_argument("--requirement")
    parser.add_argument("--ledger", help="Optional evidence-ledger.json for audited requirement coverage.")
    parser.add_argument("--audit-summary", help="Optional audit-summary.json generated by audit_evidence.py.")
    parser.add_argument("--out")
    args = parser.parse_args()

    plan_path = Path(args.plan)
    results_path = Path(args.results)
    plan = load_json(plan_path)
    results = load_json(results_path)
    artifact_dir = Path(results.get("artifactDir") or results_path.parent)
    out_path = Path(args.out) if args.out else artifact_dir / "report.md"
    requirement_text = ""
    if args.requirement:
        requirement_text = Path(args.requirement).read_text(encoding="utf-8").strip()
    ledger = load_json(Path(args.ledger)) if args.ledger else None
    audit_summary = load_json(Path(args.audit_summary)) if args.audit_summary else None

    lines = []
    lines.append("# Requirement-Driven QA Report")
    lines.append("")
    lines.append("## 1. Summary")
    lines.append("")
    lines.append(f"- Requirement result: {requirement_result(ledger, audit_summary)}")
    lines.append(f"- Probe result: {status_icon(results.get('status', 'unknown'))}")
    lines.append(f"- Base URL: {plan.get('baseUrl', '')}")
    lines.append(f"- Test time: {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"- Results file: `{results_path}`")
    lines.append("- Evidence integrity: Current-run probe evidence only. Do not treat unplanned or unexecuted requirement points as passed.")
    if audit_summary:
        audit_label = "PASS" if audit_summary.get("passed") else "FAIL"
        lines.append(f"- Evidence audit: {audit_label} (`{args.audit_summary}`)")
        lines.append(f"- Audited requirements: {audit_summary.get('requirement_count', 0)}")
    else:
        lines.append("- Evidence audit: NOT RUN. Do not treat this report as final pass/fail evidence.")
    lines.append("")

    if requirement_text:
        lines.append("## 2. Requirement Source")
        lines.append("")
        preview = requirement_text if len(requirement_text) <= 2500 else requirement_text[:2500] + "\n\n...[truncated]"
        lines.append(preview)
        lines.append("")

    lines.append("## 3. Requirement Coverage")
    lines.append("")
    if ledger:
        evidence_by_id = {item.get("id"): item for item in ledger.get("evidence", [])}
        lines.append("| Requirement | Source Evidence | Status | Evidence | Notes |")
        lines.append("| --- | --- | --- | --- | --- |")
        for req in ledger.get("requirements", []):
            evidence_bits = []
            for evidence_id in req.get("evidence_ids", []):
                ev = evidence_by_id.get(evidence_id, {})
                locator = ev.get("path") or ev.get("file") or ev.get("url") or ev.get("log_ref") or ev.get("value") or ""
                evidence_bits.append(f"{evidence_id}: {ev.get('type', '')} {locator}".strip())
            lines.append(
                "| "
                + " | ".join(
                    [
                        str(req.get("id", "")),
                        str(req.get("source", "")),
                        status_icon(req.get("status", "")),
                        "<br>".join(evidence_bits) if evidence_bits else "",
                        str(req.get("notes", "")),
                    ]
                )
                + " |"
            )
    else:
        lines.append("- No evidence ledger was provided. Requirement-level pass/fail status is not audited.")
    lines.append("")

    lines.append("## 4. Scenario Results")
    lines.append("")
    lines.append("| Scenario | Status | Failed Steps | Evidence |")
    lines.append("| --- | --- | --- | --- |")
    for scenario in results.get("scenarios", []):
        failed = [s for s in scenario.get("steps", []) if s.get("status") == "failed"]
        evidence = []
        for step in scenario.get("steps", []):
            if step.get("screenshot"):
                evidence.append(step["screenshot"])
        evidence_text = "<br>".join(f"`{e}`" for e in evidence[:5])
        lines.append(f"| {scenario.get('title') or scenario.get('id')} | {status_icon(scenario.get('status', 'unknown'))} | {len(failed)} | {evidence_text} |")
    lines.append("")

    lines.append("## 5. Step Details")
    lines.append("")
    for scenario in results.get("scenarios", []):
        lines.append(f"### {scenario.get('title') or scenario.get('id')}")
        lines.append("")
        for step in scenario.get("steps", []):
            lines.append(f"- {status_icon(step.get('status', 'unknown'))} `{step.get('action')}` {step.get('title', '')}".rstrip())
            if step.get("url"):
                lines.append(f"  - URL: {step['url']}")
            if step.get("statusCode"):
                lines.append(f"  - Status: {step['statusCode']}")
            if step.get("error"):
                lines.append(f"  - Error: {step['error']}")
            if step.get("screenshot"):
                lines.append(f"  - Screenshot: `{step['screenshot']}`")
        lines.append("")

    lines.append("## 6. Runtime Errors")
    lines.append("")
    lines.append("### Console")
    lines.append("")
    console = results.get("console", [])
    if console:
        for item in console[:50]:
            lines.append(f"- {item.get('type')}: {item.get('text')} ({item.get('url')})")
    else:
        lines.append("- None captured.")
    lines.append("")
    lines.append("### Failed Network/API Responses")
    lines.append("")
    failed_responses = results.get("failedResponses", [])
    if failed_responses:
        for item in failed_responses[:80]:
            lines.append(f"- HTTP {item.get('status')} `{item.get('url')}`")
    else:
        lines.append("- None captured.")
    lines.append("")

    lines.append("## 7. Coverage Gaps")
    lines.append("")
    if audit_summary:
        errors = audit_summary.get("errors", [])
        counts = audit_summary.get("status_counts", {})
        if errors:
            for error in errors:
                lines.append(f"- Audit error: {error}")
        elif any(counts.get(status, 0) for status in ("Failed", "Blocked", "Untested", "Inconclusive")):
            lines.append("- Audited scope still has non-passed requirement statuses:")
            for status in ("Failed", "Blocked", "Untested", "Inconclusive"):
                count = counts.get(status, 0)
                if count:
                    lines.append(f"  - {status}: {count}")
        else:
            lines.append("- None identified in the audited scope.")
        if counts:
            lines.append(f"- Requirement status counts: {json.dumps(counts, ensure_ascii=False)}")
    else:
        lines.append("- Evidence audit was not run.")
        lines.append("- Any requirement point not represented in the plan/results must be manually marked `Untested`, `Blocked`, or `Inconclusive`; never infer it as `Passed`.")
        lines.append("- Before final delivery, compare this report against the original requirement source and add missing requirement coverage rows.")
    lines.append("")

    lines.append("## 8. Screenshot Evidence")
    lines.append("")
    screenshots = []
    for scenario in results.get("scenarios", []):
        for step in scenario.get("steps", []):
            if step.get("screenshot"):
                screenshots.append(step["screenshot"])
    if screenshots:
        for idx, shot in enumerate(screenshots, 1):
            lines.append(f"### Screenshot {idx}")
            lines.append("")
            lines.append(f"![Screenshot {idx}]({shot})")
            lines.append("")
    else:
        lines.append("- No screenshots captured.")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
